### ISSUE TITLE
Can't build it neither on Xcode 9.4.1 and Xcode 10

### ISSUE THREAD

**Issue by kalafun** [Mapwize/mapwize-app-ios#2]
According to the error report, there are missing model object variables. Am I missing something?

```
Mapwize/Classes/ViewController/MapwizeViewController.swift:130:65: Value of type 'LocationProvidersManager' has no member 'lastLocation'
Mapwize/Classes/ViewController/MapwizeViewController.swift:251:22: Value of type 'MapwizePlugin' has no member 'setFollowUserMode'
MapwizeForMapbox.MapwizePlugin:11:14: Did you mean 'followUserMode'?
Mapwize/Classes/ViewController/MapwizeViewController.swift:517:73: Value of type 'LocationProvidersManager' has no member 'lastLocation'
Mapwize/Classes/ViewController/MapwizeViewController.swift:780:20: Use of unresolved identifier 'MWZDirectionOptions'
MapwizeForMapbox.MWZDirectionPoint:1:17: Did you mean 'MWZDirectionPoint'?
Metal.MTLStoreActionOptions:2:15: Did you mean 'MTLStoreActionOptions'?
Mapwize/Classes/ViewController/MapwizeViewController.swift:947:77: Value of type 'LocationProvidersManager' has no member 'lastLocation'
Mapwize/Classes/ViewController/MapwizeViewController.swift:1167:40: Value of type 'LocationProvidersManager' has no member 'lastLocation'
```

**Comment by emerciercontexeo** [comment]
Hi,

Thanks for reporting this issue.

Mapwize has not been compile with swift 4.3 at the moment. So please use Swift 4.2.

I will publish a new version for tomorrow morning to allow compilation with 4.3.

To make it works until the next release, follow this steps : 

- Update the Podfile : 
```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
target 'Mapwize' do
    use_frameworks!
    pod 'MapwizeForMapbox'
    pod 'GPSIndoorLocationProvider'
    pod 'SocketIndoorLocationProviderObjc'
    pod 'SelectorIndoorLocationProvider'
    pod 'ManualIndoorLocationProvider'
    pod 'NAOSDK'
    pod 'ionicons'
    pod 'Kingfisher', '4.9.0'
    pod 'MTBBarcodeScanner'
end
```

- Run a pod install (eventually a pod update to be sure you get all last version)

- Run the app

**Comment by kalafun** [comment]
Hey, thanks for your prompt answer!

I updated the podfile but Im still getting these errors:

Swift Compiler Error Group
.../mapwize-app-ios-master/Mapwize/Classes/LocationProvider/LocationProvidersManager.swift:87:25: Value of type 'MWZVenue' has no member 'indoorLocationProviders'
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:130:65: Value of type 'LocationProvidersManager' has no member 'lastLocation'
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:251:22: Value of type 'MapwizePlugin' has no member 'setFollowUserMode'
.../mapwize-app-ios-master/MapwizeForMapbox.MapwizePlugin:11:14: Did you mean 'followUserMode'?
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:517:73: Value of type 'LocationProvidersManager' has no member 'lastLocation'
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:780:20: Use of unresolved identifier 'MWZDirectionOptions'
.../mapwize-app-ios-master/MapwizeForMapbox.MWZDirectionPoint:1:17: Did you mean 'MWZDirectionPoint'?
.../mapwize-app-ios-master/Metal.MTLStoreActionOptions:2:15: Did you mean 'MTLStoreActionOptions'?
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:947:77: Value of type 'LocationProvidersManager' has no member 'lastLocation'
.../mapwize-app-ios-master/Mapwize/Classes/ViewController/MapwizeViewController.swift:1167:40: Value of type 'LocationProvidersManager' has no member 'lastLocation'

**Comment by kalafun** [comment]
Thanks for the answer, I have updated the pods, run pod update adn removed the nao.kml file from the project added the API_KEY and now it works!
