### ISSUE TITLE
Is it possible to do Augmented reality navigation using mapwize in xcode swift?

### ISSUE THREAD

**Issue by Parameshvadivel** [Mapwize/mapwize-app-ios#4]
I am working on indoor navigation Augmented reality. I tried many possible ways to build AR indoor navigation in iOS swift language using arkit or any other sdk but could'nt make it. Now i am trying using mapwize, is it possible to do AR indoor navigation? If yes, can you pls update your version.

Any other suggestion pls..

**Comment by mathieugerard** [comment]
Hi. No Mapwize does not provide AR indoor navigation at this point. Sorry about that.

**Comment by Parameshvadivel** [comment]
> Hi. No Mapwize does not provide AR indoor navigation at this point. Sorry about that.

Any other sdk provide with support AR indoor navigation

**Comment by mathieugerard** [comment]
We do not know any unfortunately. I'm sorry.
